---
- name: Converge
  hosts: all
  become: true

  vars:
    qemu_guest_agent_service_state: stopped  # The service can't start properly in a container

  roles:
    - role: ansible-role-qemu-guest-agent
